### PR TITLE
Added some basic CI infrastructure to nextgen Bookchain

### PR DESCRIPTION
**Pull request by ErisMik**

### CODE REVIEW

**Comment by ErisMik** [comment]
Sorry it's halfway through the work, but I figure we should start getting multiple eyes on stuff

**Review by MuchToKnow — APPROVED** [review]
Oo already starting 👀

Looks good

**Comment by MuchToKnow** [comment]
Are we planning on keeping same json block format? I guess we should discuss if we want to have a coin associated with it.

**Comment by ErisMik** [comment]
Yeah, we will need to discuss format and direction. I think it's okay to try and just reach feature parity with the hackathon version and then we can modify it from there.

**Pull request merged**
